totrt: False

# yolo 權重路徑
model:
  weight: './data/yolo_best_weight.pt'

# maskrcnn 權重路徑
maskrcnn:
  weight: './data/maskrcnn_best_weight.pt'

nms:
  conf_thres: 0.5
  iou_thres: 0.5
  classes: 0
  agnostic_nms: False

data:
  root: "Polyp"
  img_dir: "Images"
  mask_dir: "Masks"

optimizer: "Adam"

num_epochs: 200


